# Generated by Django 3.1.3 on 2020-11-28 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=250)),
                ('content', models.TextField(max_length=3500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 10, 55, 803882))),
                ('changed_date', models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 10, 55, 803882))),
                ('owner', models.CharField(max_length=150)),
                ('supporter', models.CharField(max_length=150)),
            ],
        ),
    ]
