# Generated by Django 3.1.3 on 2020-11-28 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='changed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 1, 33, 54, 599253)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 1, 33, 54, 599253)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
